# Generated by Django 3.0.4 on 2020-04-19 11:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Particularite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('nombre_visite', models.IntegerField()),
                ('nombre_mangeur', models.IntegerField(max_length=3)),
                ('difficulte', models.CharField(choices=[('F', 'Facile'), ('M', 'Moyen'), ('D', 'Difficile')], default='F', max_length=1)),
                ('cout', models.CharField(choices=[('F', 'Faible'), ('M', 'Moyen'), ('E', 'Eleve')], default='M', max_length=1)),
                ('calorie', models.IntegerField(max_length=5)),
                ('temps_preparation', models.IntegerField(max_length=4)),
                ('temps_cuisson', models.IntegerField(max_length=4)),
                ('temps_repos', models.IntegerField(max_length=4)),
                ('ustensile', models.CharField(max_length=255)),
                ('cree', models.DateTimeField(auto_now_add=True)),
                ('maj', models.DateTimeField(auto_now=True)),
                ('cuisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.Cuisson')),
                ('particularite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.Particularite')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.Type')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('url', models.CharField(max_length=255, validators=[django.core.validators.URLValidator])),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.Recette')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=1, max_digits=7)),
                ('ordre', models.IntegerField(max_length=2)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.Recette')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cree', models.DateTimeField(auto_now_add=True)),
                ('maj', models.DateTimeField(auto_now=True)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.Recette')),
            ],
        ),
    ]
