# Generated by Django 3.0.4 on 2020-04-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ordre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recette',
            name='calorie',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recette',
            name='nombre_mangeur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recette',
            name='temps_cuisson',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recette',
            name='temps_preparation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recette',
            name='temps_repos',
            field=models.IntegerField(),
        ),
    ]
