# Generated by Django 3.0.4 on 2020-04-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0002_auto_20200419_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recette',
            name='nombre_mangeur',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recette',
            name='nombre_visite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recette',
            name='temps_cuisson',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recette',
            name='temps_repos',
            field=models.IntegerField(default=0),
        ),
    ]
