# Generated by Django 3.0.4 on 2020-04-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0004_auto_20200419_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
    ]
